### ISSUE TITLE
Hubot binary in repo?

### ISSUE THREAD

**Issue by JustusAdam** [fsr/matthias#10]
Was it a deliberate choice to push the bin/ folder? should this not be in the .gitignore and not in the repository? Its a generated binary after all.

**Comment by JustusAdam** [comment]
Fixed in #11

**Comment by kiliankoe** [comment]
It's not in the default .gitignore generated by yo and makes it easier for people to clone this repo and immediately go ahead and hack on stuff.

I'd definitely go ahead and leave that in there, makes things easier and it doesn't change.

**Comment by JustusAdam** [comment]
But the hubot installation requires you to install the dependencies with node anyway and that automatically creates all the stuff in bin/

**Comment by kiliankoe** [comment]
A simple `npm install` creates the binary in the same form?

**Comment by JustusAdam** [comment]
yes

**Comment by JustusAdam** [comment]
I'll try it actually
wait ...

**Comment by kiliankoe** [comment]
It doesn't.

**Comment by kiliankoe** [comment]
```
$ ./bin/hubot
zsh: no such file or directory: ./bin/hubot
$ npm install
[...]
$ ./bin/hubot
zsh: no such file or directory: ./bin/hubot
```

**Comment by JustusAdam** [comment]
Well ... don't I look like a fool now. It doesn't, I tested it as well. How dumb is that?
