### ISSUE TITLE
Geburtstage

### ISSUE THREAD

**Issue by kiliankoe** [fsr/matthias#25]
`matthias geburtstag?` listet in wie vielen Tagen die nächste Person Geburtstag hat. Wenn Jahr vorhanden auch wie alt sie wird.

`matthias geburtstag <name>` gibt aus, in wie vielen Tagen diese Person Geburtstag hat. Wenn Jahr vorhanden... siehe oben.

`matthias geburtstag list` gibt alle bekannten Geburtstagsdaten aus.

Auch selbstständiges Posten von Geburtstagswünschen am Tag selbst?

Daten in ner .yml Datei sammeln. Natürlich nur von denen, die da drin stehen wollen.

**Comment by JustusAdam** [comment]
Also das command scheme sollte schon entweder deutsch oder englisch sein.

Ergo entweder `matthias birthday list` oder `matthias geburtstag liste`

**Comment by kiliankoe** [comment]
Denglisch all the way!

**Comment by JustusAdam** [comment]
Ich möchte dazu bemerken, dass ich für `birthday` über `geburtstag` bin, nicht zuletzt weil es 2 character kürzer ist.

**Comment by JustusAdam** [comment]
Deutsch sucks!

**Comment by kiliankoe** [comment]
> weil es 2 character kürzer ist

Also die Kommentare hier sollten schon entweder deutsch oder englisch sein :P

Aber ja, hast Recht. Einsprachig (bevorzugt Englisch) wäre sinnvoller.

**Comment by kiliankoe** [comment]
Feature 2, 3 und 4 laufen. 1 noch nicht. Falls das wer machen möchte, nur zu.

Syntax ist jetzt `matthias bday` oder `matthias birthday` oder `matthias geburtstag` mit `list` oder `liste`. Alles davon geht.

Zu klären wäre noch die im Slack aufgeschmissene Frage ob es sinnvoll ist die Geburtstage hier im Repo zu haben oder nicht. Falls nein bräuchte es bitte ne clevere Lösung dafür, da matthias' deployment aktuell auf dokku gestützt ist. Soll heißen es gibt nicht wirklich persistenten Speicher auf dem Server für Dinge außerhalb des Repos. So wie bei Heroku halt.

**Comment by kiliankoe** [comment]
Jetzt verbleibt hier nur noch moment.js davon zu überzeugen, niemals nach oben zu runden.
