### ISSUE TITLE
Fork image plugin for #nsfw channel

### ISSUE THREAD

**Issue by kiliankoe** [fsr/matthias#39]
@sjmielke wants this.

The idea is to fork [this](https://github.com/hubot-scripts/hubot-google-images) and build in support for disabling safe search in a single channel.

![yay porn](http://i.giphy.com/p0SR9IJkgiOBi.gif)

**Comment by kiliankoe** [comment]
> uniporn

~ @sjmielke

**Comment by dirkonet** [comment]
Basically, it's only about changing https://github.com/hubot-scripts/hubot-google-images/blob/master/src/google-images.coffee#L69 to be channel-aware instead of based on an environment variable, right?

**Comment by kiliankoe** [comment]
Seems like it, so basically something along the lines of `safe: msg.message.room == process.env.HUBOT_IMAGE_NSFW_ROOM ? "off" : "high"` in that line I guess.
