### ISSUE TITLE
Trim trailing spaces from input 

### ISSUE THREAD

**Issue by Feliix42** [fsr/matthias#41]
At the moment, matthias does not react to the command `mensa` but to the command `mensa`.

Before parsing the input string any trailing spaces should be removed to avoid errors.

**Comment by kiliankoe** [comment]
There should be two different things happening...

Either `mensa`, see https://github.com/fsr/matthias/blob/master/scripts/mensa.coffee#L160

or `mensa $mensa`, see https://github.com/fsr/matthias/blob/master/scripts/mensa.coffee#L163

I'll have a look later.
