### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by Feliix42** [fsr/matthias#56]
The commands are currently case sensitive. This sucks, especially when you are using Slack on your mobile phone which automatically starts every message with an upper case letter and automatically corrects every second word to upper case.

To reproduce this, simply ask matthias `Jemand da?` instead of `jemand da?`.

**Comment by kiliankoe** [comment]
Looks like some of them are, most shouldn't be though. It's a matter of an extra `i` in the regexes^^

**Comment by kiliankoe** [comment]
Not regarding the setting of the door state `jemand da?` was the *only* handler this applied to 😄
