### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Feliix42** [fsr/matthias#57]
This repository currently doesn't have a license. I suggest MIT.

Opinions welcome :)

**Comment by kiliankoe** [comment]
I'm all for MIT. Hubot itself is also MIT licensed fyi.

**Comment by Feliix42** [comment]
As far as I know, every contributor has to approve this change, right?

**Comment by kiliankoe** [comment]
That would probably be the correct thing to do. What about a PR with every contributor mentioned? It's not like we don't know everybody here 🙈

**Comment by Feliix42** [comment]
This is exactly what I wanted to do :D
