### ISSUE TITLE
Mensa ain't workin'

### ISSUE THREAD

**Issue by kiliankoe** [fsr/matthias#6]
Stupid shit ain't doing what's it's supposed to be doing. Cletus, get over 'ere and fix this dog-gone pile'o'shit!

**Comment by JustusAdam** [comment]
What's the problem?

**Comment by kiliankoe** [comment]
I'm guessing the problem lies @ openmensa. Data is rarely correct.

**Comment by JustusAdam** [comment]
Ah. Yeah that seems a bit out of reach.

**Comment by kiliankoe** [comment]
And I'd rather not start scraping here... Wanted to ask some stuff from the Studentenwerk anyways (soon-ish)...

**Comment by JustusAdam** [comment]
No I agree about the not scraping. But what exactly seems to be wrong? Is it always the same mensa? or days behind?

**Comment by kiliankoe** [comment]
Not entirely sure, but it seems like the data is always a day behind and refreshes sometime in the afternoon. But as I said, not entirely sure about this.

**Comment by JustusAdam** [comment]
Because openmensa is on github ...

**Comment by kiliankoe** [comment]
I know, don't care much though

**Comment by JustusAdam** [comment]
Might be worth at least opening an issue. But I can't do it, I can't properly describe the issue.

**Comment by kiliankoe** [comment]
Got it! Fuckers...

`$ http get http://openmensa.org/api/v2/canteens/79/days/2015-07-31/meals` is what we should be doing, not using today, which randomizes the fucking output for some idiotic reason.
